server:
  port: 8081
# h2
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/h2db
    username: micaias
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

